syntax = "proto3";
package imserver;
import "base.proto";

option cc_generic_services = true;

//用于和网关进行通信
message NewMessageRequest {
    string request_id = 1;       //请求ID -- 全链路唯一标识
    string user_id = 2;
    string session_id = 3;       //客户端身份识别信息 -- 这就是消息发送者
    string chat_session_id = 4;  //聊天会话ID -- 标识了当前消息属于哪个会话，应该转发给谁
    MessageContent message_content = 5;  // 消息内容--消息类型+内容
}
message NewMessageResponse {
    string request_id = 1;
    bool success = 2;
    string error_message = 3; 
}

//用于内部的通信,生成完整的消息信息,并获取消息的转发人员列表
message GetTransmitTargetResponse {
    string request_id = 1;
    bool success = 2;
    string error_message = 3; 
    MessageInfo message_info = 4;       //组织好的消息结构 
    repeated string target_id = 5;      //消息的转发目标
}

service MsgTransmitService {
    rpc GetTransmitTarget(NewMessageRequest) returns (GetTransmitTargetResponse);
}



