/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `userId` varchar(64) NOT NULL,
  `nickname` varchar(64) NULL,
  `description` varchar(64) NULL,
  `password` varchar(64) NULL,
  `phone` varchar(64) NULL,
  `avatarId` varchar(64) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `userId_i`
  ON `user` (`userId`);

CREATE UNIQUE INDEX `nickname_i`
  ON `user` (`nickname`);

CREATE UNIQUE INDEX `phone_i`
  ON `user` (`phone`);

